modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "LGPL-2.1+"

[[mods]]
modId = "architectury_data_generation_fix"
version = "${version}"
displayName = "Architectury Data Generation Fix"
authors = "Jab125"
description = '''
A tweak to Data Generation so that the game correctly closes after data generation.
'''
#logoFile = ""

[[dependencies.architectury_data_generation_fix]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.architectury_data_generation_fix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[features.architectury_data_generation_fix]
javaVersion="[17,)"